services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=ubuntu
      - POSTGRES_PASSWORD=sakamichi
      - POSTGRES_DB=nogi-official
    ports:
      - "5445:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql
      # - postgresql.conf:/var/lib/postgresql/data/postgresql.conf

  bigram:
    image: postgres:15
    environment:
      - POSTGRES_USER=ubuntu
      - POSTGRES_PASSWORD=sakamichi
      - POSTGRES_DB=nogi-official
    volumes:
      - bigram_volume:/var/lib/postgresql
    # - postgresql.conf:/var/lib/postgresql/data/postgresql.conf

  pgroonga:
    image: postgres:15
    environment:
      - POSTGRES_USER=ubuntu
      - POSTGRES_PASSWORD=sakamichi
      - POSTGRES_DB=nogi-official
    volumes:
      - pgroonga_volume:/var/lib/postgresql
    # - postgresql.conf:/var/lib/postgresql/data/postgresql.conf
volumes:
  postgres_volume:
  bigram_volume:
  pgroonga_volume:
